export function normalizeTeamName(value: string) {
  return value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim()
}

const TEAM_CODES: Record<string, string> = {
  mexico: 'MX',
  'estados unidos': 'US',
  eeuu: 'US',
  usa: 'US',
  canada: 'CA',
  'costa rica': 'CR',
  panama: 'PA',
  honduras: 'HN',
  guatemala: 'GT',
  'el salvador': 'SV',
  nicaragua: 'NI',
  jamaica: 'JM',
  haiti: 'HT',
  cuba: 'CU',
  'republica dominicana': 'DO',
  argentina: 'AR',
  brasil: 'BR',
  uruguay: 'UY',
  colombia: 'CO',
  ecuador: 'EC',
  chile: 'CL',
  peru: 'PE',
  paraguay: 'PY',
  bolivia: 'BO',
  venezuela: 'VE',
  españa: 'ES',
  francia: 'FR',
  inglaterra: 'GB',
  escocia: 'GB',
  gales: 'GB',
  irlanda: 'IE',
  'irlanda del norte': 'GB',
  alemania: 'DE',
  portugal: 'PT',
  italia: 'IT',
  'paises bajos': 'NL',
  holanda: 'NL',
  belgica: 'BE',
  croacia: 'HR',
  serbia: 'RS',
  suiza: 'CH',
  austria: 'AT',
  dinamarca: 'DK',
  suecia: 'SE',
  noruega: 'NO',
  finlandia: 'FI',
  polonia: 'PL',
  'republica checa': 'CZ',
  chequia: 'CZ',
  eslovaquia: 'SK',
  eslovenia: 'SI',
  hungria: 'HU',
  rumania: 'RO',
  grecia: 'GR',
  turquia: 'TR',
  ucrania: 'UA',
  moldavia: 'MD',
  bosnia: 'BA',
  montenegro: 'ME',
  albania: 'AL',
  macedonia: 'MK',
  islandia: 'IS',
  estonia: 'EE',
  letonia: 'LV',
  lituania: 'LT',
  'costa de marfil': 'CI',
  'sudafrica': 'ZA',
  marruecos: 'MA',
  argelia: 'DZ',
  tunez: 'TN',
  egipto: 'EG',
  senegal: 'SN',
  ghana: 'GH',
  nigeria: 'NG',
  camerun: 'CM',
  'arabia saudita': 'SA',
  qatar: 'QA',
  iran: 'IR',
  irak: 'IQ',
  japon: 'JP',
  'corea del sur': 'KR',
  'corea del norte': 'KP',
  china: 'CN',
  australia: 'AU',
  'nueva zelanda': 'NZ',
  'emiratos arabes unidos': 'AE',
  uzbekistan: 'UZ',
  kazajistan: 'KZ',
  indonesia: 'ID',
  tailandia: 'TH',
  vietnam: 'VN',
  jordania: 'JO',
  palestina: 'PS',
  'trinidad y tobago': 'TT',
  surinam: 'SR',
  guyana: 'GY',
}

export function getTeamFlagEmoji(teamName?: string | null) {
  if (!teamName) return '🏳️'
  const code = TEAM_CODES[normalizeTeamName(teamName)]
  if (!code) return '🏳️'
  return code
    .toUpperCase()
    .split('')
    .map((char) => String.fromCodePoint(127397 + char.charCodeAt(0)))
    .join('')
}
